export const AUTOSAVE_DEBOUNCE_MS = 2_000;
export const AUTOSAVE_MAX_WAIT_MS = 30_000;

export const RATE_BUDGET_PER_MINUTE = 60;
export const RATE_BUDGET_PER_HOUR = 400;
export const SAVE_FIXED_REQUEST_COST = 3;

export const BACKOFF_INITIAL_MS = 5_000;
export const BACKOFF_MAX_MS = 300_000;
export const RATE_LIMITED_MIN_WAIT_MS = 60_000;
export const MAX_IMMEDIATE_STALE_RETRIES = 3;

export const TRASH_PURGE_HEADROOM = 10;
export const MAX_PURGE_ENTRIES_PER_STARTUP = 100;
export const MAX_PURGE_FILES_PER_COMMIT = 2_000;
